
export const FLOWER_DESCRIPTORS: string[] = [
  'a simple rose with a thick stem',
  'a geometric tulip with sharp petals',
  'a minimalist daisy with a dotted center',
  'an abstract lotus with layered petals',
  'a delicate cherry blossom on a branch',
  'a spiky sunflower with a large head',
  'an elegant orchid with a long stem',
  'a rounded poppy with a single petal layer',
  'a star-shaped lily with six petals',
  'a bell-shaped bluebell flower',
  'a stylized iris with curved leaves',
  'a flat design lavender sprig',
  'a line art hibiscus with a prominent stamen',
  'a blocky, pixelated carnation',
  'a swirly, whimsical daffodil',
  'a five-petal pansy with a face-like pattern',
  'a graceful calla lily with a single petal',
  'a sharp-edged thistle with a spiky top',
  'a symmetrical dahlia with many small petals',
  'a cluster of tiny forget-me-nots',
  'a simple clover flower',
  'a blooming cactus flower',
  'a minimalist peony with soft edges',
  'a long-stemmed gladiolus icon',
  'a simple buttercup flower',
  'a hanging fuchsia flower icon',
  'a line-art anemone',
  'a geometric bird of paradise flower',
  'a minimalist snowdrop flower',
  'a stylized crocus blooming from the ground',
];
